name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0
          cli_config_credentials_token: ${{ secrets.YOUR_AWS_ACCESS_KEY_ID }}
          cli_config_credentials_secret: ${{ secrets.YOUR_AWS_SECRET_ACCESS_KEY }}
          cli_config_credentials_provider: env
          backend_config_key: terraform.tfstate
          backend_config_bucket: your-terraform-state-bucket
          backend_config_region: your-aws-region

      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
